# Generated by Django 6.0.4 on 2026-05-15 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_horario', models.DateTimeField(verbose_name='dia y horario')),
                ('nombre_actividad', models.CharField(max_length=200, verbose_name='nombre de la actividad')),
                ('direccion_coordinacion', models.CharField(max_length=255, verbose_name='direccion y/o coordinacion')),
                ('localidad', models.CharField(max_length=120)),
                ('lugar_actividad', models.CharField(max_length=255, verbose_name='direccion / lugar en el que se desarrollara la actividad')),
                ('poblacion_destinataria', models.CharField(max_length=200, verbose_name='poblacion destinataria')),
                ('objetivo', models.TextField()),
                ('prioridad_actividad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='prioridad de la actividad')),
                ('requerimientos_comunicacion', models.TextField(blank=True, help_text='Piezas graficas, ceremonial, gacetilla, etc.', verbose_name='requerimientos especificos de comunicacion')),
                ('informacion_brindada', models.TextField(blank=True, verbose_name='informacion brindada')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrada de agenda',
                'verbose_name_plural': 'entradas de agenda',
                'ordering': ['dia_horario'],
            },
        ),
    ]
