# Generated by Django 6.0.4 on 2026-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradaagenda',
            options={'ordering': ['mes', 'dia_horario', 'nombre_actividad'], 'verbose_name': 'entrada de agenda', 'verbose_name_plural': 'entradas de agenda'},
        ),
        migrations.AddField(
            model_name='entradaagenda',
            name='mes',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1),
        ),
        migrations.AlterField(
            model_name='entradaagenda',
            name='dia_horario',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dia y horario'),
        ),
    ]
