# Generated by Django 6.0.4 on 2026-05-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_entradaagenda_options_entradaagenda_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaagenda',
            name='nombre_actividad',
            field=models.TextField(verbose_name='nombre de la actividad'),
        ),
    ]
