# Generated by Django 6.0.4 on 2026-05-15 13:59

import agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_entradaagenda_nombre_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaagenda',
            name='mes',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=agenda.models.current_month),
        ),
    ]
