# Generated by Django 6.0.4 on 2026-05-15 14:01

import agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_entradaagenda_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaagenda',
            name='direccion_coordinacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='direccion y/o coordinacion'),
        ),
        migrations.AlterField(
            model_name='entradaagenda',
            name='localidad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='entradaagenda',
            name='lugar_actividad',
            field=models.CharField(blank=True, max_length=255, verbose_name='direccion / lugar en el que se desarrollara la actividad'),
        ),
        migrations.AlterField(
            model_name='entradaagenda',
            name='mes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=agenda.models.current_month, null=True),
        ),
        migrations.AlterField(
            model_name='entradaagenda',
            name='objetivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entradaagenda',
            name='poblacion_destinataria',
            field=models.CharField(blank=True, max_length=200, verbose_name='poblacion destinataria'),
        ),
        migrations.AlterField(
            model_name='entradaagenda',
            name='prioridad_actividad',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='prioridad de la actividad'),
        ),
    ]
