# Generated by Django 6.0.4 on 2026-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_split_dia_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradaagenda',
            options={'ordering': ['mes', 'fecha', 'horario_inicio', 'nombre_actividad'], 'verbose_name': 'entrada de agenda', 'verbose_name_plural': 'entradas de agenda'},
        ),
        migrations.RenameField(
            model_name='entradaagenda',
            old_name='horario',
            new_name='horario_inicio',
        ),
        migrations.AlterField(
            model_name='entradaagenda',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='horario inicio'),
        ),
        migrations.AddField(
            model_name='entradaagenda',
            name='horario_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='horario fin'),
        ),
    ]
