# Generated by Django 6.0.4 on 2026-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_entradaagenda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaagenda',
            name='realizada',
            field=models.BooleanField(default=False, help_text='Marcar como realizada para disminuir su prioridad en la visualización.', verbose_name='realizada'),
        ),
    ]
